language: go
go:
  - 1.8.x
  - tip
services:
  - docker
before_install:
  - pushd test/docker && docker build -t nsscache-go:latest . && popd
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
