---
language: go

go:
  - "1.15.x"
  - "1.16.x"
  - "1.x"

install:
  - pushd docker && docker build -t nsscache-go:latest . && popd
  - go get github.com/mattn/goveralls
  - go mod vendor

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci

env:
  - GO111MODULE=on
