[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.20"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault-plugin-secrets-kv"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
